name-template: 'New Feature'  # Release name
tag-template: 'v$NEXT_PATCH_VERSION'  # Automatic version incrementing
template: |
  ## Overview:
  This release introduces new features, improvements, and bug fixes.

  ## New Features:
  $CHANGES: features

  ## Improvements:
  $CHANGES: improvements

  ## Bug Fixes:
  $CHANGES: bugs

categories:
  - title: Features
    labels:
      - feature
  - title: Improvements
    labels:
      - enhancement
      - perf
  - title: Bug Fixes
    labels:
      - bug
      - fix

draft: true  # Keep the release in draft mode initially
<<<<<<< HEAD
target: master  # Set the branch for releases
=======
target: master  # Set the branch for releases
>>>>>>> 17d5d81ce1a8639c96aa8f810322ad1ab3d92e4b
