name: Release Drafter

on:
  push:
    branches:
      - master  # Branch where PRs are merged

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update draft release
        uses: release-drafter/release-drafter@v5
